# Generated by Django 2.2.7 on 2020-01-25 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('empaquetado', models.BooleanField(default=False)),
                ('paquetes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidadPaquete', models.IntegerField(null=True)),
                ('sueltas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('existencias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('medida', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paquetes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidadesSueltas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidades', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('existencias', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Producto')),
            ],
        ),
    ]
