# Generated by Django 2.2.7 on 2020-01-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_sueltas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empaquetado',
            field=models.BooleanField(default=False),
        ),
    ]
