# Generated by Django 2.2.7 on 2020-01-24 21:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_empaquetado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidadPaquetes', models.IntegerField()),
                ('cantidadTotal', models.IntegerField()),
                ('existencias', models.DecimalField(decimal_places=2, default=0, max_digits=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
